server:
  port: 80
spring:
  application:
    name: springcloud-consumer-order
  cloud:
    consul:
      host: 192.168.137.141
      port: 8500
      discovery:
        service-name: ${spring.application.name}