server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      #单机
#      defaultZone: http://eureka7001.com:7001/eureka/
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
          # 如果enabled设置为false，则请求超时交给ribbon控制,此时@HystrixProperty(name = "execution.isolation
          #.thread.timeoutInMilliseconds", value = "5000")不起效
          # 如果enabled设置为true, 则hystrix也有对超时的控制权，@HystrixProperty(name = "execution.isolation
          #.thread.timeoutInMilliseconds", value = "5000")起效果
          # 且如果enabled设置为true，ribbon，hystrix都有对请求超时的控制权，且控制效果一样
        isolation:
          thread:
            timeoutInMilliseconds: 5000

